### ISSUE TITLE
status 200 em ceps inválidos

### ISSUE THREAD

**Issue by marcoazevedo01** [viniciussanchez/viacep#4]
Olá, estava fazendo um trabalho acadêmico e percebi que o webservice está devolvendo status 200 para ceps que não existem, no caso só peguei esse da imagem mas tive o mesmo resultado com outros valores.
Assim quando eu vou ler o json do callback ele esta com os valores 'undefined', tratei o erro com um simples if verificando se tem a key do cep no json.
Abri esse issue apenas no intuito de relatar o ocorrido. 

![testErro](https://user-images.githubusercontent.com/37423042/114250885-8a925000-9975-11eb-9b3e-d11fd54dc798.png)

**Comment by viniciussanchez** [comment]
Obrigado pela colaboração, embora o retorno do WS não tenha como eu alterar...
Talvez tenha algum lugar la no WS do viacep que você possa informar o problema com o status code, onde nesse cenário, caberia um 404 mesmo.
