### ISSUE TITLE
Uso indevido

### ISSUE THREAD

**Issue by HerickRaposo** [viniciussanchez/viacep#6]
Boa tarde, sou desenvolvedor da Empresa Mury Contábil em São Lourenço -MG, atualmente em nossos sistemas estamos tendo um alto fluxo de informações, sendo assim durante a implementação de uma nova funcionalidade onde necessita da validação de cep  fui bloqueado não conseguindo acesso ao site nem conseguindo fazer as consultas, gostaria de saber quais são as boas práticas de consumo, qual o limite de consulta que posso fazer e se esse limite é dado por minutos, por hora ou diário. Aguardo retorno!

**Comment by viniciussanchez** [comment]
Boa tarde... cara isso é um bloqueio do próprio ViaCEP e não na biblioteca aqui.
Da uma olhada no site deles, na documentação deve estar falando algo referente a quantidade de requisições por minuto
https://viacep.com.br/

**Comment by HerickRaposo** [comment]
Obrigado, infelizmente não falam nada
